// The season rollover, replayed. Every season label, game date, stats file, Sleeper and ESPN report, and the clock itself is moved forward one year,
// so any year written into the logic would show. Then the two awkward real cases: pre-season (no 2027 stats yet) and offseason (no 2027 schedule yet).
import fs from "fs"; import { execFileSync } from "child_process";
const SCEN = process.env.SCEN; const rd = (f) => fs.readFileSync("/tmp/nfl/" + f, "utf8"); const YR = 2027, PREV = 2026, OFFSET = 364 * 864e5;
const split = (l) => { const o = []; let cur = "", q = false; for (const ch of l.replace(/\r$/, "")) { if (ch === '"') q = !q; else if (ch === "," && !q) { o.push(cur); cur = ""; } else cur += ch; } o.push(cur); return o; };
const join = (c) => c.map((x) => (/[",]/.test(x) ? `"${x.replace(/"/g, '""')}"` : x)).join(",");
const SCENARIOS = {
  "monday-final": { espnWeek: 4, status: () => "post", want: 5, mnf: true }, "sunday-night": { espnWeek: 4, status: (i, n) => (i === n - 1 ? "pre" : "post"), want: 4 }, "tuesday-roll": { espnWeek: 5, status: () => "pre", want: 5 },
  "week18-final": { espnWeek: 18, status: () => "post", want: 18 }, "preseason": { espnWeek: 1, status: () => "pre", want: 1, blankYear: true, sleeperType: "pre", teams: true }, "offseason-no-schedule": { espnWeek: null, empty: true, want: 1, dropYear: true, sleeperType: "off", teams: true } };
if (!SCEN) { let pass = 0, fail = 0; const t = (n, c, x = "") => { c ? pass++ : fail++; console.log(`${c ? "PASS" : "FAIL"}  ${n}${x ? "  -> " + x : ""}`); }; const only = (process.env.ONLY || "").split(",").filter(Boolean);
  for (const [name, s] of Object.entries(SCENARIOS)) { if (only.length && !only.includes(name)) continue; let out; try { out = JSON.parse(execFileSync("node", [process.argv[1]], { env: { ...process.env, SCEN: name }, encoding: "utf8", timeout: 85000, stdio: ["ignore", "pipe", "pipe"] }).trim().split("\n").pop()); } catch (e) { out = { error: String(e.stderr || e.message).split("\n").filter(Boolean).pop() }; }
    const o = out;
    if (name === "monday-final") { t(`${YR}: when the last game of week 4 ends the app moves to week 5, exactly as it did in 2026`, o.active === 5 && o.feedWeek === 5 && !o.error, JSON.stringify(o).slice(0, 200)); t("the feed counts every game final, and Teams moves on with it (week 4 done, next game week 5)", o.weekInfo?.final === o.weekInfo?.total && o.teams?.doneWeek === 4 && o.teams?.throughWeek === 4 && o.teams?.jaxNext === 5, JSON.stringify(o.teams)); t("the rankings' arrows compare week 4 with week 3, and the season on the payload is 2027", o.teams?.prevFromWeek3 === true && o.season === YR, JSON.stringify({ season: o.season })); t("the stadium roof comes through the schedule into the team payload as text (not a number), so kicker pages can show it", Array.isArray(o.teams?.roofs) && o.teams.roofs.some((r) => typeof r === "string" && r.length > 2), JSON.stringify(o.teams?.roofs)); }
    if (name === "sunday-night") t(`${YR}: before Monday night ends the app stays on week 4`, o.active === 4 && o.feedWeek === 4 && o.teams?.doneWeek === 3, JSON.stringify(o).slice(0, 200));
    if (name === "tuesday-roll") t(`${YR}: Tuesday after the flip, still week 5`, o.active === 5 && o.feedWeek === 5, JSON.stringify(o).slice(0, 200));
    if (name === "week18-final") t(`${YR}: after the last week the app stays on week 18, never week 19`, o.active === 18 && o.feedWeek === 18, JSON.stringify(o).slice(0, 200));
    if (name === "preseason") { t("pre-season 2027 (new schedule, no 2027 results, no 2027 stats file): the feed shows week 1 with no error", o.feedWeek === 1 && !o.error && !/error|unavailable/i.test(o.notes || ""), JSON.stringify(o).slice(0, 240));
      t("Teams still builds: 32 teams, nothing played yet, every team flagged early, ratings carried over from 2026 (not blank)", o.teams?.n === 32 && o.teams?.throughWeek === 0 && o.teams?.allEarly === true && o.teams?.ratedFromPrior === true && o.teams?.firstWeek === 1, JSON.stringify(o.teams)); }
    if (name === "offseason-no-schedule") { t("offseason (Sleeper already says 2027, no 2027 schedule published yet): the feed shows week 1 quietly", o.feedWeek === 1 && !/error|unavailable/i.test(o.notes || ""), JSON.stringify(o).slice(0, 240));
      t("Teams keeps showing last season's final table (all 32 teams, week 18 done) and says the 2027 schedule is not out yet", !o.teamsCrash && o.teams?.n === 32 && o.teams?.season === 2026 && o.teams?.fallback?.wanted === 2027 && o.teams?.fallback?.season === 2026 && o.teams?.doneWeek === 18, JSON.stringify(o.teams || o.teamsCrash)); } }
  console.log(`\n${pass} passed, ${fail} failed`); process.exit(fail ? 1 : 0); }
else { const S = SCENARIOS[SCEN]; const RD = Date; globalThis.Date = class extends RD { constructor(...a) { if (a.length === 0) super(RD.now() + OFFSET); else super(...a); } static now() { return RD.now() + OFFSET; } };
  const L = rd("games.csv").split("\n"), H = split(L[0]), ix = Object.fromEntries(H.map((h, i) => [h, i]));
  const shiftDay = (d) => (d && /^\d{4}-\d\d-\d\d$/.test(d) ? new RD(RD.parse(d + "T00:00:00Z") + OFFSET).toISOString().slice(0, 10) : d);
  const rows = L.slice(1).filter(Boolean).map((l) => split(l)).map((c) => { c[ix.season] = String(+c[ix.season] + 1); c[ix.gameday] = shiftDay(c[ix.gameday]); return c; });
  const keep = rows.filter((c) => !(S.dropYear && c[ix.season] === String(YR)));
  for (const c of keep) { if (S.blankYear && c[ix.season] === String(YR)) { c[ix.home_score] = ""; c[ix.away_score] = ""; } if (S.mnf && c[ix.season] === String(YR) && c[ix.game_type] === "REG" && c[ix.week] === "4") { const mon = c[ix.away_team] === "JAX" && c[ix.home_team] === "CIN"; if (mon || c[ix.home_score] === "" || c[ix.home_score] === "NA") { c[ix.home_score] = "20"; c[ix.away_score] = mon ? "24" : "17"; } } }
  const gamesText = [L[0], ...keep.map(join)].join("\n"); const wk = (w) => keep.filter((c) => c[ix.season] === String(YR) && c[ix.game_type] === "REG" && Number(c[ix.week]) === w);
  const event = (c, st, i, W) => ({ id: `e${W}${i}`, date: `${c[ix.gameday]}T17:00Z`, week: { number: W }, competitions: [{ competitors: [{ homeAway: "home", team: { abbreviation: c[ix.home_team] }, score: st === "pre" ? "0" : "20" }, { homeAway: "away", team: { abbreviation: c[ix.away_team] }, score: st === "pre" ? "0" : "24" }], status: { type: { state: st, completed: st === "post", detail: st === "post" ? "Final" : "" } } }], status: { type: { state: st, completed: st === "post" } } });
  globalThis.fetch = async (u) => { u = String(u); const R = (b, s = 200) => new Response(typeof b === "string" ? b : JSON.stringify(b), { status: s });
    if (u.includes("espn.com") && u.includes("scoreboard")) { if (S.empty) return R({ week: { number: null }, season: { year: YR }, events: [] }); const q = new URL(u).searchParams.get("week"), W = q ? Number(q) : S.espnWeek, g = wk(W); return R({ week: { number: W }, season: { year: YR }, events: g.map((c, i) => event(c, W === S.espnWeek ? S.status(i, g.length) : "pre", i, W)) }); }
    if (u.includes("state/nfl")) return R({ season: String(YR), week: S.espnWeek ?? 1, season_type: S.sleeperType || "regular" });
    if (u.endsWith("players/nfl")) { const ids = rd("ids.csv").split("\n"), HH = split(ids[0]), jx = Object.fromEntries(HH.map((h, i) => [h, i])), out = {}; for (const l of ids.slice(1)) { const c = split(l), sid = c[jx.sleeper_id]; if (!sid || sid === "NA") continue; out[sid] = { player_id: sid, full_name: c[jx.name], position: c[jx.position], team: c[jx.team], status: "Active", gsis_id: c[jx.gsis_id] }; } return R(out); }
    if (u.includes("schedules/games.csv")) return R(gamesText); const m = u.match(/stats_player_week_(\d{4})\.csv/); if (m) { const y = +m[1]; if (y === PREV) return R(rd("stats_2025.csv")); if (y === YR && !S.blankYear && !S.dropYear) return R(rd("stats_2026.csv")); return R("x", 404); }
    if (u.includes("db_playerids")) return R(rd("ids.csv")); return R("x", 404); };
  const { activeWeek } = await import("/home/claude/edge/netlify/functions/lib/espn.mjs"); const { buildFeed } = await import("/home/claude/edge/netlify/functions/feed.mjs"); const out = {};
  try { out.active = (await activeWeek()).week; } catch (e) { out.active = null; out.activeError = e.message; }
  try { const feed = await buildFeed(null); out.feedWeek = feed.week; out.notes = (feed.notes || []).join(" | "); } catch (e) { out.error = "feed: " + e.message; }
  try { const h = (await import("/home/claude/edge/netlify/functions/feed.mjs")).default; const r = await h(new Request("http://x/api/feed")); const b = await r.json(); out.weekInfo = b.weekInfo; out.season = b.season; } catch (e) { out.weekInfoError = e.message; }
  if (["monday-final", "sunday-night", "preseason", "offseason-no-schedule"].includes(SCEN)) { try { const { computeTeams } = await import("/home/claude/edge/netlify/functions/lib/teamstats.mjs"); const T = await computeTeams(); const codes = Object.keys(T.teams || {});
      out.teams = { n: codes.length, doneWeek: T.doneWeek, throughWeek: T.throughWeek, season: T.season, jaxNext: T.teams?.JAX?.ahead?.[0]?.week, prevFromWeek3: T.teams?.JAX ? T.teams.JAX.trend.length === T.throughWeek : null, fallback: T.fallback, roofs: (T.teams?.JAX?.ahead || []).map((a) => a.roof ?? null), allEarly: codes.length ? codes.every((c) => T.teams[c].early) : null, ratedFromPrior: codes.length ? codes.some((c) => T.teams[c].rating !== 0 && T.teams[c].rating != null) && new Set(codes.map((c) => T.teams[c].rating)).size > 5 : null, firstWeek: T.teams?.JAX?.ahead?.[0]?.week }; } catch (e) { out.teamsCrash = e.message; } }
  console.log(JSON.stringify(out)); }
